model: "gpt-4"

prompts:
  - Please write me a one paragraph horoscope based on my brithday, which is BIRTHDAY. I would like the horoscope to be glasses-themed and inspired by STYLE_DESCRIPTOR. Please feel free to make it silly. Also, please do not mention any actual glasses brands.
  - Please write me a three sentence horoscope based on my brithday, which is BIRTHDAY. The horoscope must include a prediction one something that will happen to me. I would like the horoscope to be glasses-themed and inspired by STYLE_DESCRIPTOR. Please do not mention any actual glasses brands.
